"""
Переводы подписей очереди — руками, без API.

⚠️ Зачем отдельный файл. Эти строки закрывали автоматические формы
(`11-stat-forms.json`), а он собирает имена по словарям. Когда часть записей
выпала из очереди при пересборке, имён стало меньше — и правил с 1460 упало
до 852. Подписи вроде «Balance: 1,234» перестали переводиться.

Строки простые и однотипные, поэтому переводим сами: правило проекта прямо
велит не звать API там, где справишься руками.

⚠️ Значки Hypixel в ключе непечатаемы и при копировании превращаются в пробел.
Поэтому сопоставление идёт по тексту БЕЗ значков, а сами значки возвращаются
из оригинала на места меток {i1}, {i2} — тот же приём, что в
`gen_enchant_sections.py`.
"""

# Подписи вида «Имя: {n}» — из них генератор форм и собирает имена.
LABELS = {
    "All-time Chocolate": "Шоколада за всё время",
    "Arrow Damage": "Урон стрел",
    "Available eggs": "Доступно яиц",
    "BRONZE medals": "Бронзовых медалей",
    "Balance": "Баланс",
    "Base Ability Damage Bonus": "Базовый бонус урона способности",
    "Bits Available": "Доступно Bits",
    "Blocks Mined": "Добыто блоков",
    "Bonus Charges": "Бонусные заряды",
    "Bonus Critical Damage": "Бонусный урон крита",
    "Bonus Defense": "Бонусная защита",
    "Bonus Fossil Essence": "Бонусная Fossil Essence",
    "Bonus Speed": "Бонусная скорость",
    "Boss Collections Unlocked": "Открыто коллекций боссов",
    "Candy Score": "Очки конфет",
    "Chocolate this Prestige": "Шоколада за этот престиж",
    "Cleanup": "Очистка",
    "Coins per Kill": "Монет за убийство",
    "Collection Unlocked": "Открыто коллекции",
    "Collections Unlocked": "Открыто коллекций",
    "Combat Exp": "Опыт боя",
    "Commissions Completed": "Выполнено поручений",
    "Contests Completed": "Пройдено состязаний",
    "Contributions": "Вклад",
    "Crops Harvested": "Собрано урожая",
    "Crystals": "Кристаллы",
    "Current Damage Bonus": "Текущий бонус урона",
    "Current LVL": "Текущий уровень",
    "Current Max Pets": "Предел числа питомцев",
    "Current Speed Cap": "Текущий предел скорости",
    "Current balance": "Текущий баланс",
    "Currently Active": "Сейчас активно",
    "Deaths": "Смертей",
    "Dungeon Chests Opened": "Открыто сундуков подземелий",
    "Dungeons": "Подземелья",
    "Duplicates Found": "Найдено повторов",
    "Election Votes": "Голосов на выборах",
    "Families Completed": "Собрано семейств",
    "Families Found": "Найдено семейств",
    "GOLD medals": "Золотых медалей",
    "Gifted coins": "Подарено монет",
    "Gifts Given": "Подарено подарков",
    "Global drops": "Общая добыча",
    "Highest Accessory Power": "Наибольшая Accessory Power",
    "Highlight Chance": "Шанс подсветки",
    "Kuudra Chests Opened": "Открыто сундуков Kuudra",
    "Levels left to Unlock": "Уровней до открытия",
    "Logs Cut": "Срублено брёвен",
    "Max Rabbit Hitman Slots": "Предел ячеек Rabbit Hitman",
    "Max interest": "Предел процентов",
    "Melee Damage": "Урон в ближнем бою",
    "Pelts": "Шкуры",
    "Placeable": "Можно поставить",
    "Popularity Lvl": "Уровень популярности",
    "Purse Coins": "Монеты в кошельке",
    "Rare drops found with this pet": "Редкой добычи с этим питомцем",
    "Recipe Book Unlocked": "Открыто книги рецептов",
    "Recipes Unlocked": "Открыто рецептов",
    "Required to fuse": "Нужно для сплава",
    "Rewards Unlocked": "Открыто наград",
    "SILVER medals": "Серебряных медалей",
    "Selected Pitch": "Выбранный наклон",
    "Selected Yaw": "Выбранный поворот",
    "Sharks Killed": "Убито акул",
    "Skeletor Kills": "Убийств Skeletor",
    "SkyBlock Level": "Уровень SkyBlock",
    "Spawn Chance": "Шанс появления",
    "Spawn Weight": "Вес появления",
    "Stored Fuel": "Запас топлива",
    "Throw Distance": "Дальность броска",
    "Times Visited": "Посещений",
    "Total Collected": "Всего собрано",
    "Total Completions": "Всего прохождений",
    "Total Enchanting EXP": "Всего опыта Enchanting",
    "Total Fishing EXP": "Всего опыта Fishing",
    "Total Months Subscribed": "Месяцев подписки",
    "Total Players Fluxed": "Всего игроков во Flux",
    "Total Progress": "Общий прогресс",
    "Total Tier IV Kills": "Всего убийств ступени IV",
    "Total Tiers Unlocked": "Всего открыто ступеней",
    "Total contributions": "Всего вклада",
    "Tuning Points": "Очки настройки",
    "Walk Speed": "Скорость ходьбы",
    "Wood collections": "Коллекции древесины",
    "XP Orbs": "Сферы опыта",
    "XP Task Completion": "Выполнение задачи на XP",
    "Year": "Год",
    "You've bought": "Куплено",
    "You've dropped": "Выброшено",
    "Your Pet Score": "Твой Pet Score",
    "Your level": "Твой уровень",
    "Your Crimson Essence": "Твоя Crimson Essence",
    "Your Diamond Essence": "Твоя Diamond Essence",
    "Your Dragon Essence": "Твоя Dragon Essence",
    "Your Forest Essence": "Твоя Forest Essence",
    "Your Fossil Essence": "Твоя Fossil Essence",
    "Your Gold Essence": "Твоя Gold Essence",
    "Your Ice Essence": "Твоя Ice Essence",
    "Your Spider Essence": "Твоя Spider Essence",
    "Your Undead Essence": "Твоя Undead Essence",
    "Your Wither Essence": "Твоя Wither Essence",
    "Equipment Wardrobe Slots": "Ячейки гардероба снаряжения",
    "Loadout Slots": "Ячейки снаряжения",
    "Monthly Gems": "Gems в месяц",
    "Profile Slots": "Ячейки профилей",
    "Wardrobe Slots": "Ячейки гардероба",
    "Mythological Bestiary Tiers": "Ступени Bestiary мифологии",
}

# Строки целиком — там, где подпись не выделить.
WHOLE = {
    "Click here to view it!": "Нажми, чтобы посмотреть!",
    "Event: Season of Jerry": "Событие: Season of Jerry",
    "You have {n} unclaimed leveling reward!":
        "У тебя {n} неполученная награда за уровень!",
    "You are being transferred to the Prototype Lobby for being AFK!":
        "Тебя переносит в Prototype Lobby за бездействие!",
    "{s} joined the lobby!": "{s} зашёл в лобби!",
    "Grants +{n} Cold Resistance.": "Даёт +{n} к сопротивлению холоду.",
    "Increases  Crit Damage by {n}%.": "Повышает {i1} урон крита на {n}%.",
    "Capped at {n} Intelligence.": "Не больше {n} интеллекта.",
    "Automatically smelts broken blocks": "Автоматически переплавляет добытые",
    "into their smelted form.": "блоки.",
    "Additionally, enemies drop +{n} coins": "Кроме того, враги роняют +{n} монет",
    "when killed.": "при убийстве.",
    "of combat.": "боя.",
    "drops.": "добычи.",
    "(Max {n} Defense)": "(Максимум {n} защиты)",
}
